[project]
name = "clipabit-backend"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]",
    "python-multipart",
    "ffmpeg-python",
    "opencv-python-headless",
    "numpy",
    "modal",
]

